import ErrorHook
# ErrorHook.init()

# print(1/0)
# print(a)
raise BaseException('I am a Error.')
# while True:
#     pass